### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ryuseinii** [ryuseinii/furima-39473#20]
# URL
https://furima-39473.onrender.com

# Basic認証のIDとパスワード
ID：admin
PW：2222

# 出品者用のメールアドレスとパスワード
email：abcd1234@sample.com
pw：abcd1234

# 購入者用のメールアドレスとパスワード
email：abcd5678@sample.com
pw：abcd5678

**Comment by shodai-ito** [comment]
@ryuseinii さん、ご提出ありがとうございます‼︎
動作確認を行ったところ、ユーザー登録をした段階で下記の画面になってしまいました。
<img width="1168" alt="スクリーンショット 2023-11-29 9 27 51" src="https://github.com/ryuseinii/furima-39473/assets/62537107/0906025d-faf3-493a-8240-d8de51d3f611">

以降、時間を置いても同様のエラーが出るため、サーバーに負荷がかかるコードもしくは設定になっている可能性があります。
今一度、ご自身の方でも本番環境でアプリが開けるか確認いただけますと幸いです。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by ryuseinii** [comment]
早速のコメント有難うございます！
立ち上がりに少し時間を要しますが、こちらでは添付の通り問題なく見れております。
[https://gyazo.com/72f9e45c73b4a4281e7395e58582c806](url)

お手数をおかけしますが再度ご確認頂きたくお願い致します。

**Comment by shodai-ito** [comment]
@ryuseinii さん、再度ご提出ありがとうございます‼︎
アプリが問題なく開けること確認いたしました。
上記一時的なエラーだった可能性があります。お手数をおかけしました。

改めて動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`出品機能`**
- [x] **商品の状態は、「---、新品・未使用、未使用に近い、目立った傷や汚れなし、やや傷や汚れあり、傷や汚れあり、全体的に状態が悪い」の7項目が表示されること（--- は初期値として設定すること）**
「新品」と「未使用」の区切りを「、」から「・」に変更しましょう。
カテゴリーの項目は「・」で区切っているため、統一感を出しましょう。

- [x] **配送料の負担は、「---、着払い(購入者負担)、送料込み(出品者負担)」の3項目が表示されること（--- は初期値として設定すること）**
「送料払い」という言葉はあまり馴染みがないため、「送料込み」もしくは「元払い」としておきましょう。
<img width="630" alt="スクリーンショット 2023-11-29 10 22 57" src="https://github.com/ryuseinii/furima-39473/assets/62537107/3450e975-263f-488f-8788-9a7dee15608a">

- [x] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
最初は機能しますが、一度出品に失敗すると、それ以降手数料と利益が自動で変わらなくなります。

### **`購入機能`**
- [x] **必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができること**
クレジットカード情報を入力することができず、購入ができません。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by ryuseinii** [comment]
ご指摘有難うございます。4点すべて修正完了し本番環境でも動作確認できました。
ご確認の程お願い致します。

必要な情報を適切に入力して「購入」ボタンを押すと、商品の購入ができること
[https://gyazo.com/51ef1356ea61c044a6c66515d7b75f46](url)

**Comment by shodai-ito** [comment]
@ryuseinii さん、 修正作業ありがとうございます！

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます！
最終課題「FURIMA」の開発、お疲れ様でした。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
